# Generated by Django 3.2.16 on 2023-01-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_alter_notificacion_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='level',
            field=models.CharField(choices=[('Success', 'success'), ('Info', 'info'), ('Wrong', 'wrong'), ('Cualquiera', 'cualquiera'), ('Servicio solicitado', 'servicio_solicitado'), ('Servicio pagado', 'servicio_pagado'), ('Servicio cancelado', 'servicio_cancelado')], default='Cualquiera', max_length=20),
        ),
    ]
