# Generated by Django 3.2.16 on 2023-01-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canalmensaje',
            name='check_leido',
        ),
        migrations.DeleteModel(
            name='CheckMensajeLeido',
        ),
    ]
