# Generated by Django 3.2.16 on 2022-10-28 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20220823_1557'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='usuarios',
            field=models.ManyToManyField(blank=True, through='chat.CanalUsuario', to='empresa.usuario'),
        ),
        migrations.AlterField(
            model_name='canalmensaje',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.usuario'),
        ),
        migrations.AlterField(
            model_name='canalusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.usuario'),
        ),
    ]
