# Generated by Django 3.2.16 on 2022-12-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='id_servicio',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
