# Generated by Django 3.2.16 on 2023-01-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20230103_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='canalmensaje',
            name='check_leido',
            field=models.CharField(default='1250680269', max_length=30),
            preserve_default=False,
        ),
    ]
