# Generated by Django 3.2.16 on 2022-12-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_canal_id_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='canalmensaje',
            name='leido',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
