# Generated by Django 3.2.16 on 2022-10-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_canalusuario_canal'),
    ]

    operations = [
        migrations.AddField(
            model_name='canalmensaje',
            name='estado',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
