# Generated by Django 3.2.16 on 2023-01-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_canalmensaje_check_leido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canalmensaje',
            name='check_leido',
            field=models.CharField(max_length=100),
        ),
    ]
