# Generated by Django 3.2.16 on 2022-11-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_canalmensaje_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='servicio',
            field=models.TextField(default='guardia'),
            preserve_default=False,
        ),
    ]
