# Generated by Django 3.2.16 on 2022-11-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_canal_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='servicio',
            field=models.CharField(choices=[('CA', 'custodia armada'), ('GS', 'guardia seguridad'), ('TM', 'transportar mercaderia'), ('CS', 'chofer seguro')], max_length=20),
        ),
    ]
