# Generated by Django 3.2.16 on 2022-11-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_canal_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='servicio',
            field=models.CharField(choices=[('custodia', 'custodia'), ('guardia', 'guardia'), ('transportar', 'transportar'), ('chofer', 'chofer')], max_length=20),
        ),
    ]
