# Generated by Django 3.2.16 on 2022-11-16 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_canal_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canalmensaje',
            name='estado',
        ),
    ]
