# Generated by Django 3.2.16 on 2022-11-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_canalmensaje_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='servicio',
            field=models.CharField(choices=[('Custodia Armada', 'Custodia Armada'), ('Transporte de productos', 'Transporte de productos'), ('Chofer seguro', 'Chofer seguro'), ('Guardia de seguridad', 'Guardia de seguridad')], max_length=23),
        ),
    ]
