# Generated by Django 3.2.16 on 2022-11-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_canal_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='servicio',
            field=models.CharField(choices=[('Custodia', 'Custodia Armada'), ('Transporte', 'Transporte de productos'), ('Chofer', 'Chofer seguro'), ('Guardia', 'Guardia de seguridad')], max_length=23),
        ),
    ]
