# Generated by Django 3.2.16 on 2022-11-22 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='texto',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='detalle_mensaje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.detallemensaje'),
            preserve_default=False,
        ),
    ]
