# Generated by Django 3.2.16 on 2022-11-22 02:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_auto_20221121_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='actualizar',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='tiempo',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
