# Generated by Django 3.2.16 on 2022-11-22 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_auto_20221121_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='detalle_mensaje',
        ),
        migrations.DeleteModel(
            name='DetalleMensaje',
        ),
    ]
