# Generated by Django 3.2.16 on 2022-11-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_auto_20221121_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='texto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
