# Generated by Django 3.2.16 on 2022-11-22 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_mensaje_texto2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='texto',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='texto2',
        ),
    ]
