# Generated by Django 3.2.16 on 2022-11-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_auto_20221121_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='actualizar',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='tiempo',
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
