# Generated by Django 3.2.16 on 2022-12-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteInicioSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(default='', max_length=70)),
                ('contrasenha', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(default='', max_length=70)),
                ('nombres', models.CharField(default='', max_length=70)),
                ('cedula', models.IntegerField(default='')),
                ('fNacimiento', models.DateField(default='')),
                ('sexo', models.CharField(default='', max_length=70)),
                ('correo', models.CharField(default='', max_length=70)),
                ('telefono', models.IntegerField(default='')),
                ('contrasenha', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
