# Generated by Django 3.2.16 on 2022-10-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienteWA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteInicioSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(default='', max_length=70)),
                ('contrasenha', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
