# Generated by Django 3.2.15 on 2022-08-23 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('idCargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('Ad', 'administrativo'), ('Op', 'operativo')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='personalAdministrativo',
            fields=[
                ('idPersonal', models.AutoField(primary_key=True, serialize=False)),
                ('inicioOperanciones', models.DateField(auto_now_add=True)),
                ('finOpeaciones', models.DateField(auto_now_add=True)),
                ('fechaModificacion', models.DateField(auto_now=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.cargo')),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.usuario')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.estado')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='publicidad',
            fields=[
                ('idPublicidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=50)),
                ('correoCliente', models.CharField(max_length=50)),
                ('numeroTelf', models.CharField(max_length=50)),
                ('fechaInicioPubli', models.DateField(auto_now_add=True)),
                ('fechaFinPubli', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.personaladministrativo')),
            ],
        ),
    ]
