# Generated by Django 3.2.16 on 2022-12-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tokenMovil',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
