# Generated by Django 3.2.16 on 2022-12-21 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_remove_usuario_tokenmovil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='administrador_Encargado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='personal_Encargado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresa.personaloperativo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Personal_Operativo',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='empresa.usuario')),
                ('idPersonal', models.AutoField(primary_key=True, serialize=False)),
                ('numCedula', models.CharField(max_length=10, unique=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.estado')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.sucursal')),
            ],
            bases=('empresa.usuario',),
        ),
    ]
