# Generated by Django 3.2.16 on 2023-01-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_estadopedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadopedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Proceso', 'Proceso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], max_length=20),
        ),
    ]
