# Generated by Django 3.2.16 on 2022-11-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20220823_1557'),
    ]
'''
    operations = [
        migrations.RemoveField(
            model_name='armamento',
            name='municion',
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='fechaCeseOperaciones',
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='fechaIngreso',
        ),
        migrations.RemoveField(
            model_name='personaloperativo',
            name='agregadoPor',
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='municion',
        ),
        migrations.DeleteModel(
            name='tipoEquipamiento',
        ),
    ]
'''