# Generated by Django 3.2.16 on 2023-01-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_personaloperativo_cargo_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='idPedido',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
