# Generated by Django 3.2.16 on 2022-11-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20220823_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobil',
            name='contrasenia',
            field=models.CharField(default=1234, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobil',
            name='usuarioApp',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
