# Generated by Django 3.2.16 on 2023-01-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_alter_pedido_idpedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='idPedido',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='idServicio',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
