# Generated by Django 3.2.16 on 2023-01-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_auto_20230127_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='idServicio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
