# Generated by Django 3.2.16 on 2023-01-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_alter_estadopedido_idestadop'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='destino',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='duracion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='origen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
