# Generated by Django 3.2.16 on 2022-11-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_auto_20221123_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='equipamiento',
            fields=[
                ('idEquipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='estadoPedido',
            fields=[
                ('idEstadoP', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('En Espera', 'En Espera'), ('En Curso', 'En Curso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='metodoPago',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False)),
                ('metodo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tipoServicio',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tarifa', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='publicidad',
            name='costo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaNac',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('placa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('anio', models.IntegerField()),
                ('idEquipamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.equipamiento')),
            ],
        ),
        migrations.CreateModel(
            name='tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numTarjeta', models.CharField(max_length=16)),
                ('banco', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('debito', 'debito'), ('credito', 'credito')], max_length=10)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='personalOperativo',
            fields=[
                ('idPersonal', models.AutoField(primary_key=True, serialize=False)),
                ('numCedula', models.CharField(max_length=10, unique=True)),
                ('apellidos', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('fechaNac', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'masculino'), ('F', 'femenino')], max_length=30)),
                ('direccion', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=70, unique=True)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('fotoOp', models.ImageField(upload_to='uploads/')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.estado')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='mobil',
            fields=[
                ('numeroCell', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('idEquipamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.equipamiento')),
            ],
        ),
        migrations.CreateModel(
            name='detallePerfilOp',
            fields=[
                ('idDetallePerfil', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.cargo')),
                ('idPersonalOp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.personaloperativo')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.usuario'),
        ),
        migrations.CreateModel(
            name='candado',
            fields=[
                ('numSerie', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('anio', models.IntegerField()),
                ('idEquipamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.equipamiento')),
            ],
        ),
        migrations.CreateModel(
            name='armamento',
            fields=[
                ('numSerie', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=20)),
                ('clase', models.CharField(max_length=20)),
                ('idEquipamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.equipamiento')),
            ],
        ),
    ]
